all: odbc.dll
    @:

odbc.dll: odbc.obj
    cl /LD odbc.obj /link /OUT:odbc.dll /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x86" odbc32.lib

odbc.obj: odbc.c
    cl /c odbc.c 

.PHONY: all